from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 874)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_component1 = QtWidgets.QComboBox(self.frame_2)
        self.comboBox_component1.setObjectName("comboBox_component1")
        self.comboBox_component1.addItem("")
        self.comboBox_component1.addItem("")
        self.comboBox_component1.addItem("")
        self.comboBox_component1.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_component1, 0, 1, 1, 1)
        self.label_img1 = QtWidgets.QLabel(self.frame_2)
        self.label_img1.setText("")
        self.label_img1.setObjectName("label_img1")
        self.gridLayout_2.addWidget(self.label_img1, 1, 0, 1, 1)
        self.label_component1_2 = QtWidgets.QLabel(self.frame_2)
        self.label_component1_2.setText("")
        self.label_component1_2.setObjectName("label_component1_2")
        self.gridLayout_2.addWidget(self.label_component1_2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 2)
        self.comboBox_output = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_output.setObjectName("comboBox_output")
        self.comboBox_output.addItem("")
        self.comboBox_output.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_output, 0, 2, 1, 2)
        self.comboBox_mix1 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_mix1.setObjectName("comboBox_mix1")
        self.comboBox_mix1.addItem("")
        self.comboBox_mix1.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_mix1, 1, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setMaximum(100)
        self.gridLayout_5.addWidget(self.horizontalSlider, 1, 1, 1, 2)
        self.gain1 = QtWidgets.QLabel(self.frame_4)
        self.gain1.setText("")
        self.gain1.setObjectName("gain1")
        self.gridLayout_5.addWidget(self.gain1, 1, 3, 1, 1)
        self.comboBox_component_choose1 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_component_choose1.setObjectName("comboBox_component_choose1")
        self.comboBox_component_choose1.addItem("")
        self.comboBox_component_choose1.addItem("")
        self.comboBox_component_choose1.addItem("")
        self.comboBox_component_choose1.addItem("")
        self.comboBox_component_choose1.addItem("")
        self.comboBox_component_choose1.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_component_choose1, 2, 0, 1, 4)
        self.comboBox_mix2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_mix2.setObjectName("comboBox_mix2")
        self.comboBox_mix2.addItem("")
        self.comboBox_mix2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_mix2, 3, 0, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.frame_4)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_2.setMinimum(0)
        self.horizontalSlider_2.setMaximum(100)
        self.gridLayout_5.addWidget(self.horizontalSlider_2, 3, 1, 1, 2)
        self.gain2 = QtWidgets.QLabel(self.frame_4)
        self.gain2.setText("")
        self.gain2.setObjectName("gain2")
        self.gridLayout_5.addWidget(self.gain2, 3, 3, 1, 1)
        self.comboBox_component_choose2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_component_choose2.setObjectName("comboBox_component_choose2")
        self.comboBox_component_choose2.addItem("")
        self.comboBox_component_choose2.addItem("")
        self.comboBox_component_choose2.addItem("")
        self.comboBox_component_choose2.addItem("")
        self.comboBox_component_choose2.addItem("")
        self.comboBox_component_choose2.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_component_choose2, 4, 0, 1, 4)
        self.gridLayout.addWidget(self.frame_4, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_component2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_component2.setObjectName("comboBox_component2")
        self.comboBox_component2.addItem("")
        self.comboBox_component2.addItem("")
        self.comboBox_component2.addItem("")
        self.comboBox_component2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_component2, 0, 1, 1, 1)
        self.label_img2 = QtWidgets.QLabel(self.frame_3)
        self.label_img2.setText("")
        self.label_img2.setObjectName("label_img2")
        self.gridLayout_3.addWidget(self.label_img2, 1, 0, 1, 1)
        self.label_component2 = QtWidgets.QLabel(self.frame_3)
        self.label_component2.setText("")
        self.label_component2.setObjectName("label_component2")
        self.gridLayout_3.addWidget(self.label_component2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.gain1_2 = QtWidgets.QLabel(self.frame_5)
        self.gain1_2.setObjectName("gain1_2")
        self.gridLayout_6.addWidget(self.gain1_2, 0, 1, 1, 1)
        self.output1 = QtWidgets.QLabel(self.frame_5)
        self.output1.setText("")
        self.output1.setObjectName("output1")
        self.gridLayout_6.addWidget(self.output1, 1, 0, 1, 1)
        self.output2 = QtWidgets.QLabel(self.frame_5)
        self.output2.setText("")
        self.output2.setObjectName("output2")
        self.gridLayout_6.addWidget(self.output2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuopen_images = QtWidgets.QMenu(self.menubar)
        self.menuopen_images.setObjectName("menuopen_images")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionimages = QtWidgets.QAction(MainWindow)
        self.actionimages.setObjectName("actionimages")
        self.actionNew_file = QtWidgets.QAction(MainWindow)
        self.actionNew_file.setObjectName("actionNew_file")
        self.menuopen_images.addAction(self.actionimages)
        self.menuopen_images.addAction(self.actionNew_file)
        self.menubar.addAction(self.menuopen_images.menuAction())
        self.list_combobox=[self.comboBox_component_choose1,self.comboBox_component_choose2,self.comboBox_mix1,self.comboBox_mix2,self.comboBox_output]
        self.list_sliders=[self.horizontalSlider,self.horizontalSlider_2]
        self.list_combobox_image_component=[self.comboBox_component1,self.comboBox_component2]
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "IMAGE 1"))
        self.comboBox_component1.setItemText(0, _translate("MainWindow", "magnitude"))
        self.comboBox_component1.setItemText(1, _translate("MainWindow", "phase"))
        self.comboBox_component1.setItemText(2, _translate("MainWindow", "real"))
        self.comboBox_component1.setItemText(3, _translate("MainWindow", "imag"))
        self.label.setText(_translate("MainWindow", "Mixer output to"))
        self.comboBox_output.setItemText(0, _translate("MainWindow", "output1"))
        self.comboBox_output.setItemText(1, _translate("MainWindow", "output2"))
        self.comboBox_mix1.setItemText(0, _translate("MainWindow", "image1"))
        self.comboBox_mix1.setItemText(1, _translate("MainWindow", "image 2"))
        self.comboBox_component_choose1.setItemText(0, _translate("MainWindow", "Mag"))
        self.comboBox_component_choose1.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_component_choose1.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_component_choose1.setItemText(3, _translate("MainWindow", "Imag"))
        self.comboBox_component_choose1.setItemText(4, _translate("MainWindow", "Uni Mag"))
        self.comboBox_component_choose1.setItemText(5, _translate("MainWindow", "Uni Phase"))
        self.comboBox_mix2.setItemText(0, _translate("MainWindow", "image 2"))
        self.comboBox_mix2.setItemText(1, _translate("MainWindow", "image 1"))
        self.comboBox_component_choose2.setItemText(0, _translate("MainWindow", "Mag"))
        self.comboBox_component_choose2.setItemText(1, _translate("MainWindow", "Phase"))
        self.comboBox_component_choose2.setItemText(2, _translate("MainWindow", "Real"))
        self.comboBox_component_choose2.setItemText(3, _translate("MainWindow", "Imag"))
        self.comboBox_component_choose2.setItemText(4, _translate("MainWindow", "Uni Mag"))
        self.comboBox_component_choose2.setItemText(5, _translate("MainWindow", "Uni Phase"))
        self.label_4.setText(_translate("MainWindow", "IMAGE 2"))
        self.comboBox_component2.setItemText(0, _translate("MainWindow", "magnitude"))
        self.comboBox_component2.setItemText(1, _translate("MainWindow", "phase"))
        self.comboBox_component2.setItemText(2, _translate("MainWindow", "real"))
        self.comboBox_component2.setItemText(3, _translate("MainWindow", "imag"))
        self.label_2.setText(_translate("MainWindow", "Output1"))
        self.gain1_2.setText(_translate("MainWindow", "Output2"))
        self.menuopen_images.setTitle(_translate("MainWindow", "file"))
        self.actionimages.setText(_translate("MainWindow", "open images"))
        self.actionNew_file.setText(_translate("MainWindow", "New file"))